wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1646172818
    t:
      1:
      - 2
      - 3
      - 5
      2:
      - 2
      - 3
      - 5
      3:
      - 2
      - 3
      - 8
      - 19
      4: 3.10.2
      5: 0.12.10
      8:
      - 1
      - 3
      - 5
learning_rate:
  desc: null
  value: 0.0001
